apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slack-agent
  template:
    metadata:
      labels:
        app: slack-agent
    spec:
      containers:
      - name: slack-agent
        image: slack-agent:latest
        env:
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-secrets
              key: bot-token
        - name: SLACK_SIGNING_SECRET
          valueFrom:
            secretKeyRef:
              name: slack-secrets
              key: signing-secret
        - name: PORT
          value: "3000"
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 30 